---
title: "Single-Cell Expression Projection"
author: "Altair Wei"
date: "2024-07-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../scripts/LoadUtils.R", chdir = TRUE)
inputs <- list()
```

## Inputs

Change input parameters bellow:

```{r}
# Ensembl ID of wheat genome
inputs$gene_to_query <- "TraesCS5B02G039000"

# Dimensionality Reduction: umap or tsne
inputs$dimred <- "umap"

# Order cell points on UMAP/t-SNE by expression value?
inputs$order_by_expression <- TRUE

# Show text label on UMAP/t-SNE plots
inputs$label_cell_types <- TRUE
```

```{r results='asis', echo=FALSE}
for (par in names(inputs)) {
  cat(sprintf("- **%s**: %s\n", par, inputs[[par]]))
}
```

## Load Objects

Load necessary data objects:

```{r}
obj <- readRDS(Sys.glob("../objects/obj_annotated_*.rds"))
sce <- Seurat::as.SingleCellExperiment(obj, assay = "RNA")
sce <- muscat::prepSCE(sce, kid = "ident", gid = "group", sid = "sample", drop = FALSE)
```

```{r}
all_celltypes <- c(
   "Gu", "Ep_1", "Ep_2",
  "Me_1", "Me_2", "Me_3", "Me_4", "Me_5", "Me_6",
  "Va_1", "Va_2", "Va_3", "Va_4",
  "BS", "CC", "MPV_1", "MPV_2")

all_celltype_colors <- ggthemes::tableau_color_pal("Tableau 20")(length(all_celltypes))
names(all_celltype_colors) <- all_celltypes
```

```{r}
all_body_layers <- c(
  "Gu"    = "L1",
  "Ep_1"  = "L1",
  "Ep_2"  = "L1",
  "Me_1"  = "L2",
  "Me_2"  = "L2",
  "Me_3"  = "L2",
  "Me_4"  = "L2",
  "Me_5"  = "L2",
  "Me_6"  = "L2",
  "Va_1"  = "L2",
  "Va_2"  = "L2",
  "Va_3"  = "L2",
  "Va_4"  = "L2",
  "BS"    = "L3",
  "CC"    = "L3",
  "MPV_1" = "L3",
  "MPV_2" = "L3"
)

all_tissues <- c(
  Gu   = "Stomata",
  Ep_1 = "Epidermis",
  Ep_2 = "Epidermis",
  Me_1 = "Chlorenchyma",
  Me_2 = "Chlorenchyma",
  Me_3 = "Chlorenchyma",
  Me_4 = "Parenchyma",
  Me_5 = "Parenchyma",
  Me_6 = "Parenchyma",
  Va_1 = "Chlorenchyma",
  Va_2 = "Outer sheath",
  Va_3 = "Outer sheath",
  Va_4 = "Outer sheath",
  BS = "Inner sheath",
  CC = "Phloem",
  MPV_1 = "Procambium",
  MPV_2 = "Procambium"
)

all_tissues_colors <- structure(
  names = c("Stomata",      "Epidermis",    "Chlorenchyma", "Parenchyma",
            "Outer sheath", "Inner sheath", "Phloem",       "Procambium"),
  .Data = c("#4e79a7",      "#f28e2b",      "#8cd17d",      "#b6992d",
            "#86bcb6",      "#e15759",      "#ff9d9a",      "#79706e")
)


obj$tissue <- do.call(
  dplyr::recode, c(list(.x = Seurat::Idents(obj)), as.list(all_tissues)))
obj$tissue <- forcats::fct_relevel(obj$tissue, names(all_tissues_colors))
```

## Plot Cell Types on UMAP/t-SNE

```{r}
Seurat::DimPlot(obj, reduction = inputs$dimred, group.by = "tissue", label = inputs$label_cell_types) +
  ggplot2::coord_fixed() +
  ggplot2::scale_color_manual(values = all_tissues_colors) +
  theme_dimred()
```

## Project Expression on UMAP/t-SNE

```{r}
Seurat::FeaturePlot(obj, inputs$gene_to_query, reduction = inputs$dimred, order = inputs$order_by_expression) +
  ggplot2::coord_fixed() +
  theme_dimred()
```

